In [ ]:
#code snippet 1
#Installing h2o
!pip install h2o

Collecting h2o
  Downloading h2o-3.46.0.7-py2.py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from h2o) (2.32.4)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from h2o) (0.9.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->h2o) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->h2o) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->h2o) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->h2o) (2025.8.3)
Downloading h2o-3.46.0.7-py2.py3-none-any.whl (265.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.9/265.9 MB 4.9 MB/s eta 0:00:00
Installing collected packages: h2o
Successfully installed h2o-3.46.0.7

In [ ]:
#code snippet 2
#Importing h2o
import h2o

#initialize h2o
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "11.0.28" 2025-07-15; OpenJDK Runtime Environment (build 11.0.28+6-post-Ubuntu-1ubuntu122.04.1); OpenJDK 64-Bit Server VM (build 11.0.28+6-post-Ubuntu-1ubuntu122.04.1, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.12/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpfm02qh66
  JVM stdout: /tmp/tmpfm02qh66/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmpfm02qh66/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.
Warning: Your H2O cluster version is (4 months and 28 days) old.  There may be a newer version available.
Please download and install the latest version from: https://h2o-release.s3.amazonaws.com/h2o/latest_stable.html

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         05 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.7
H2O_cluster_version_age:    4 months and 28 days
H2O_cluster_name:           H2O_from_python_unknownUser_pb6q45
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.170 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.12.11 final
--------------------------  -----------------------------------------------------------------------------------------

In [ ]:
# Code snippet 3
# Importing dataset
data = h2o.import_file('https://raw.githubusercontent.com/Imjuandiaz/churn-data/refs/heads/main/WA_Fn-UseC_-Telco-Customer-Churn.csv')


data

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

customerID    gender      SeniorCitizen  Partner    Dependents      tenure  PhoneService    MultipleLines     InternetService    OnlineSecurity    OnlineBackup    DeviceProtection    TechSupport    StreamingTV    StreamingMovies    Contract        PaperlessBilling    PaymentMethod                MonthlyCharges    TotalCharges  Churn
------------  --------  ---------------  ---------  ------------  --------  --------------  ----------------  -----------------  ----------------  --------------  ------------------  -------------  -------------  -----------------  --------------  ------------------  -------------------------  ----------------  --------------  -------
7590-VHVEG    Female                  0  Yes        No                   1  No              No phone service  DSL                No                Yes             No                  No             No             No                 Month-to-month  Yes                 Electronic check                      29.85           29.85  No
5575-GNVDE    Male                    0  No         No                  34  Yes             No                DSL                Yes               No              Yes                 No             No             No                 One year        No                  Mailed check                          56.95         1889.5   No
3668-QPYBK    Male                    0  No         No                   2  Yes             No                DSL                Yes               Yes             No                  No             No             No                 Month-to-month  Yes                 Mailed check                          53.85          108.15  Yes
7795-CFOCW    Male                    0  No         No                  45  No              No phone service  DSL                Yes               No              Yes                 Yes            No             No                 One year        No                  Bank transfer (automatic)             42.3          1840.75  No
9237-HQITU    Female                  0  No         No                   2  Yes             No                Fiber optic        No                No              No                  No             No             No                 Month-to-month  Yes                 Electronic check                      70.7           151.65  Yes
9305-CDSKC    Female                  0  No         No                   8  Yes             Yes               Fiber optic        No                No              Yes                 No             Yes            Yes                Month-to-month  Yes                 Electronic check                      99.65          820.5   Yes
1452-KIOVK    Male                    0  No         Yes                 22  Yes             Yes               Fiber optic        No                Yes             No                  No             Yes            No                 Month-to-month  Yes                 Credit card (automatic)               89.1          1949.4   No
6713-OKOMC    Female                  0  No         No                  10  No              No phone service  DSL                Yes               No              No                  No             No             No                 Month-to-month  No                  Mailed check                          29.75          301.9   No
7892-POOKP    Female                  0  Yes        No                  28  Yes             Yes               Fiber optic        No                No              Yes                 Yes            Yes            Yes                Month-to-month  Yes                 Electronic check                     104.8          3046.05  Yes
6388-TABGU    Male                    0  No         Yes                 62  Yes             No                DSL                Yes               Yes             No                  No             No             No                 One year        No                  Bank transfer (automatic)             56.15         3487.95  No
[7043 rows x 21 columns]

In [ ]:
#code snippet 4
#Importing Kmeans Estimator
from h2o.estimators.kmeans import H2OKMeansEstimator

In [ ]:
#code snippet 5
#setting the number of clusters in the data train as 4
kmeans_model = H2OKMeansEstimator(k=6)

#Train the clustering model
kmeans_model.train(training_frame=data)

kmeans Model Build progress: |

/usr/local/lib/python3.12/dist-packages/h2o/estimators/estimator_base.py:192: RuntimeWarning: Dropping bad and constant columns: [customerID]
  warnings.warn(mesg["message"], RuntimeWarning)

███████████████████████████████████████████████████| (done) 100%

Model Details
=============
H2OKMeansEstimator : K-means
Model Key: KMeans_model_python_1756060434102_1


Model Summary:
    number_of_rows    number_of_clusters    number_of_categorical_columns    number_of_iterations    within_cluster_sum_of_squares    total_sum_of_squares    between_cluster_sum_of_squares
--  ----------------  --------------------  -------------------------------  ----------------------  -------------------------------  ----------------------  --------------------------------
    7043              6                     16                               10                      38886.9                          81535                   42648.1

ModelMetricsClustering: kmeans
** Reported on train data. **

Total Within Cluster Sum of Square Error: 38886.436163940205
Total Sum of Square Error to Grand Mean: 81535.00046323304
Between Cluster Sum of Square Error: 42648.56429929283

Centroid Statistics:
    centroid    size    within_cluster_sum_of_squares
--  ----------  ------  -------------------------------
    1           1683    10951.2
    2           1525    6660.2
    3           601     3127.88
    4           490     2953.1
    5           1457    9023.97
    6           1287    6170.1

Scoring History:
    timestamp            duration    iterations    number_of_reassigned_observations    within_cluster_sum_of_squares
--  -------------------  ----------  ------------  -----------------------------------  -------------------------------
    2025-08-24 18:34:16  0.156 sec   0             nan                                  nan
    2025-08-24 18:34:17  1.486 sec   1             7043                                 52175.2
    2025-08-24 18:34:18  1.687 sec   2             1006                                 40079.1
    2025-08-24 18:34:18  1.810 sec   3             96                                   39882.7
    2025-08-24 18:34:18  1.948 sec   4             427                                  39631
    2025-08-24 18:34:18  2.079 sec   5             318                                  39408.3
    2025-08-24 18:34:18  2.170 sec   6             208                                  39205.9
    2025-08-24 18:34:18  2.246 sec   7             196                                  39107.8
    2025-08-24 18:34:18  2.306 sec   8             154                                  39015.3
    2025-08-24 18:34:18  2.437 sec   9             179                                  38893.5
    2025-08-24 18:34:18  2.520 sec   10            21                                   38886.9

[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [ ]:
#code snippet 6
#Displaying the cluster size
kmeans_model.size()

[1683.0, 1525.0, 601.0, 490.0, 1457.0, 1287.0]

In [ ]:
#code snippet 7
#importing pandas
import pandas as pd

# predicts clusters on the rows
pred = kmeans_model.predict(data)

# join to original df
data_with_clusters = data.cbind(pred)

# import to pandas
df = data_with_clusters.as_data_frame()

# setting numerical variable: getting mean by cluster
numeric_summary = df.groupby("predict")[["tenure", "MonthlyCharges", "TotalCharges"]].mean()

# setting categorical variable: getting mean by cluster
categorical_cols = ["gender", "SeniorCitizen", "Partner", "Dependents",
                    "PhoneService", "MultipleLines", "InternetService",
                    "OnlineSecurity", "OnlineBackup", "DeviceProtection",
                    "TechSupport", "StreamingTV", "StreamingMovies",
                    "Contract", "PaperlessBilling", "PaymentMethod"]

categorical_summary = df.groupby("predict")[categorical_cols].agg(lambda x: x.mode()[0])

kmeans prediction progress: |████████████████████████████████████████████████████| (done) 100%

/usr/local/lib/python3.12/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"

In [ ]:
# combine resume
cluster_profiles = numeric_summary.join(categorical_summary)

# importing csv for Clusters caracteristics
cluster_profiles.to_csv("cluster_profiles.csv")

print(cluster_profiles)

            tenure  MonthlyCharges  TotalCharges  gender  SeniorCitizen  \
predict
0        58.608437       89.510606   5238.211973    Male              0
1        30.566557       21.080262    665.645458    Male              0
2        15.091514       73.601997   1099.423295  Female              1
3        54.730612       93.470612   5102.730102  Female              1
4        20.095402       52.022787   1074.271970  Female              0
5        13.652681       83.520008   1171.879138  Female              0

        Partner Dependents PhoneService MultipleLines InternetService  \
predict
0           Yes         No          Yes           Yes     Fiber optic
1            No         No          Yes            No              No
2            No         No          Yes           Yes     Fiber optic
3           Yes         No          Yes           Yes     Fiber optic
4            No         No          Yes            No             DSL
5            No         No          Yes            No     Fiber optic

              OnlineSecurity         OnlineBackup     DeviceProtection  \
predict
0                        Yes                  Yes                  Yes
1        No internet service  No internet service  No internet service
2                         No                   No                   No
3                         No                  Yes                  Yes
4                         No                   No                   No
5                         No                   No                   No

                 TechSupport          StreamingTV      StreamingMovies  \
predict
0                        Yes                  Yes                  Yes
1        No internet service  No internet service  No internet service
2                         No                   No                   No
3                         No                  Yes                  Yes
4                         No                   No                   No
5                         No                   No                   No

               Contract PaperlessBilling              PaymentMethod
predict
0              Two year              Yes  Bank transfer (automatic)
1              Two year               No               Mailed check
2        Month-to-month              Yes           Electronic check
3        Month-to-month              Yes           Electronic check
4        Month-to-month              Yes               Mailed check
5        Month-to-month              Yes           Electronic check

***Anomalys***

In [ ]:
#code snippet 1
#Installing pyod package for anormaly detection algorithms (knn)
!pip install pyod

Collecting pyod
  Downloading pyod-2.0.5-py3-none-any.whl.metadata (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.3/46.3 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from pyod) (1.5.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from pyod) (3.10.0)
Requirement already satisfied: numpy>=1.19 in /usr/local/lib/python3.12/dist-packages (from pyod) (2.0.2)
Requirement already satisfied: numba>=0.51 in /usr/local/lib/python3.12/dist-packages (from pyod) (0.60.0)
Requirement already satisfied: scipy>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from pyod) (1.16.1)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from pyod) (1.6.1)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.51->pyod) (0.43.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->pyod) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pyod) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pyod) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pyod) (4.59.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pyod) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pyod) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pyod) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pyod) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->pyod) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->pyod) (1.17.0)
Downloading pyod-2.0.5-py3-none-any.whl (200 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.6/200.6 kB 16.7 MB/s eta 0:00:00
Installing collected packages: pyod
Successfully installed pyod-2.0.5

In [ ]:
#code snippet 2
#Importing pyod
from pyod.models.knn import KNN

In [ ]:
# Code snippet 3
# Importing the dataset
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/Imjuandiaz/churn-data/refs/heads/main/WA_Fn-UseC_-Telco-Customer-Churn.csv')


data

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [ ]:
# Code snippet 4
# Create new dataset with only numerical columns
numeric_dataset = data.select_dtypes(include=['float64', 'int64'])
numeric_dataset

      SeniorCitizen  tenure  MonthlyCharges
0                 0       1           29.85
1                 0      34           56.95
2                 0       2           53.85
3                 0      45           42.30
4                 0       2           70.70
...             ...     ...             ...
7038              0      24           84.80
7039              0      72          103.20
7040              0      11           29.60
7041              1       4           74.40
7042              0      66          105.65

[7043 rows x 3 columns]

In [ ]:
# Code snippet 5
# Training with the KNN algorithm to identify the anomalies
ad_model = KNN()
ad_model.fit(numeric_dataset)

KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [ ]:
# Code snippet 6
#Predict anomalies (1 = normal, -1 = Anomaly)
anomaly_labels = ad_model.labels_
anomaly_scores = ad_model.decision_scores_

In [ ]:
# Code snippet 7
# Adding the anomaly results to the original dataframe
data['Anomaly_Label'] = anomaly_labels
data['Anomaly_Score'] = anomaly_scores
data

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Anomaly_Label,Anomaly_Score
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0,0.650000
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,One year,No,Mailed check,56.95,1889.5,No,1,1.950000
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,0,0.600000
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,1,2.724427
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,0,0.250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No,0,1.077033
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No,0,0.750000
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No,0,1.192686
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes,0,1.000000
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No,0,1.001249

In [ ]:
# Code snippet 8
# Exporting the dataset to a csv file with anomaly info
data.to_csv('Churn_KNN_Anomalies.csv', index=False)

In [ ]:
# Code snippet 9
# Displaying the number of anomalies
num_anomalies = (data['Anomaly_Label'] == 1).sum()
print(f"Number of anomalies: {num_anomalies}")

Number of anomalies: 703